const bananaImages = {
    'Regular Banana': 'images/banana.png',
    'Cheese Banana': 'images/rotten_banana.png',
    'Golden Banana': 'images/golden_banana.png',
    'Rainbow Banana': 'images/rainbow_banana.png',
    'Cosmic Banana': 'images/cosmic_banana.gif',
    'Legendary Banana': 'images/legendary_banana.png',
    // Case skins
    'Green Banana': 'images/green_banana.png',
    'Spotted Banana': 'images/spotted_banana.png',
    'Curved Banana': 'images/curved_banana.png',
    'Blue Banana': 'images/blue_banana.png',
    'Striped Banana': 'images/striped_banana.png',
    'Glowing Banana': 'images/glowing_banana.png',
    'Gold Banana': 'images/gold_banana.png',
    'Crystal Banana': 'images/crystal_banana.png',
    'Fire Banana': 'images/fire_banana.png',
    'Pinkglownana': 'images/pinkglownana.png',
    'Infernana': 'images/infernana.png',
    'Heartratenana': 'images/heartratenana.gif',
    'Rubiknana': 'images/rubiknana.gif',
    'Angelnana': 'images/angelnana.png',
    'Wizardnana': 'images/wizardnana.png',
    'Bananamobile': 'images/bananamobile.png',
    'Moainana': 'images/moainana.png',
    'Furnana': 'images/furnana.gif',
    'Christmasnana': 'images/christmasnana.gif',
    'Sushinana': 'images/sushinana.png',
    'Craftynana': 'images/craftynana.gif',
    'Glitchnana': 'images/glitchnana.png',
    'Moonglassnana': 'images/moonglassnana.gif',
    'Noisenana': 'images/noisenana.gif',
    'Goatnana': 'images/goatnana.png',
    'Noodlenana': 'images/noodlenana.png',
    'Cashnana': 'images/cashnana.gif',
    'Radarnana': 'images/radarnana.gif',
    'Screamnana': 'images/screamnana.png',
    'Cashnana': 'images/cashnana.gif',
    'Gamblenana': 'images/gamblenana.gif',
    'Pumpkinnana': 'images/pumpkinnana.gif',
    'Blossomnana': 'images/blossomnana.png',
    'Dnanana': 'images/dnanana.gif',
    'Gubbynana': 'images/gubbynana.png',
    'Heatnana': 'images/heatnana.gif',
    'Flamenana': 'images/flamenana.gif',
    'Luminousnana': 'images/luminousnana.gif',
    'Frozenana': 'images/frozenana.gif',
    'Rainana': 'images/rainana.gif'
};
